
;;;; readme.org ---  description



;;; Copyright (C) 2012 Roman V. Prikhodchenko



;;; Author: Roman V. Prikhodchenko <chujoii@gmail.com>
;;; Keywords: xattr tag search



;;;    This file is part of xattr-tag.
;;;
;;;    xattr-tag is free software: you can redistribute it and/or modify
;;;    it under the terms of the GNU General Public License as published by
;;;    the Free Software Foundation, either version 3 of the License, or
;;;    (at your option) any later version.
;;;
;;;    xattr-tag is distributed in the hope that it will be useful,
;;;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;;    GNU General Public License for more details.
;;;
;;;    You should have received a copy of the GNU General Public License
;;;    along with xattr-tag.  If not, see <http://www.gnu.org/licenses/>.



;;; Usage:

;; read with emacs



;;; History:

;; Version 0.1 was created at 2012.february.03



;;; Code:




*    enable xattr (USE flag in make.conf)
 sudo mount -oremount,user_xattr
    or permanently enable by editing:
 /etc/fstab/dev/sdb1 /export ext3 defaults,user_xattr 1 2
    Testing if extended attribute works:

*    set
 setfattr -n user.foo -v bar hello.txt

*    list of tag
 getfattr hello.txt

*    get
 getfattr -n user.foo hello.txt
    file: hello.txtuser.foo="bar"
    or:
 getfattr -d hello.txt

*    remove
 setfattr -x user.foo hello.txt


*    Backup all extended attributes:
 getfattr --dump * > data_file

*    Restore all extended attributes
 setfattr --restore=data_file

* use cli
 cp --preserve=xattr
     or
 cp --preserve=all
     or
 rsync ?????????????????


* examples:


user.checksum.md5
user.checksum.sha1
user.checksum.sha256
user.original_author
user.application
user.project
user.comment
user.icon.svg
user.icon.png.32
user.tag     :( already used:
user.tag.artist
user.tag.title
user.metatag
